version: '3.3'
services:
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - "mongodata:/data/db"
    environment:
    - DB_NAME=quices
    networks:
      - network1

volumes:
   mongodata:

networks:
   network1: