version: '3'
services:
  web:
    image: "ulearn-quizzes-ms"
    build: .
    command: "go run main.go"
    ports:
      - "7777:8080"
    depends_on:
      - "ulearn-quizzes-db"

  ulearn-quizzes-db:
    image: mongo:latest
    ports:
      - "7778:27017"